services:
  - type: web
    name: billing-dashboard
    env: python
    pythonVersion: 3.12.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn billing_dashboard:server --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
